name: Fly Deploy
on:
  push:
    branches:
      - master
  permissions:
    actions: write
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      with:
        repository: 1k32k2/Day_countdown
        token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}